//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangMayTinh2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhSanPham
    {
        public int HinhAnhID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public string DuongDanAnh { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> LaHinhChinh { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
