//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangMayTinh2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSequence
    {
        public int SequenceID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
