//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangMayTinh2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamGoiYTheoDanhGia
    {
        public int GoiYID { get; set; }
        public int SanPhamIDGoc { get; set; }
        public int SanPhamIDGoiY { get; set; }
        public int ItemsetSize { get; set; }
        public double Support { get; set; }
        public double Confidence { get; set; }
        public double Lift { get; set; }
        public Nullable<double> DiemDanhGia { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<double> DiemPhoBien { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<bool> DaLoc { get; set; }
        public Nullable<System.DateTime> NgayLoc { get; set; }
        public string DuocLoc { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual SanPham SanPham1 { get; set; }
    }
}
