//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangMayTinh2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamThuongMuaCung
    {
        public int SanPhamID1 { get; set; }
        public int SanPhamID2 { get; set; }
        public Nullable<int> SoLanMuaCung { get; set; }
        public Nullable<double> Confidence { get; set; }
        public Nullable<double> Lift { get; set; }
        public Nullable<double> Support { get; set; }
        public Nullable<bool> DaLoc { get; set; }
        public Nullable<System.DateTime> NgayLoc { get; set; }
        public string DuocLoc { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual SanPham SanPham1 { get; set; }
    }
}
