//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangMayTinh2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.DanhGia1 = new HashSet<DanhGia>();
            this.GioHang = new HashSet<GioHang>();
            this.HinhAnhSanPham = new HashSet<HinhAnhSanPham>();
            this.SanPhamLienQuan = new HashSet<SanPhamLienQuan>();
            this.SanPhamLienQuan1 = new HashSet<SanPhamLienQuan>();
            this.SanPhamThuongMuaCung = new HashSet<SanPhamThuongMuaCung>();
            this.SanPhamThuongMuaCung1 = new HashSet<SanPhamThuongMuaCung>();
            this.UserViews = new HashSet<UserViews>();
            this.KhuyenMai = new HashSet<KhuyenMai>();
            this.SanPhamYeuThich = new HashSet<SanPhamYeuThich>();
            this.ProductSequence = new HashSet<ProductSequence>();
            this.UserBehavior = new HashSet<UserBehavior>();
            this.SanPhamGoiYTheoDanhGia = new HashSet<SanPhamGoiYTheoDanhGia>();
            this.SanPhamGoiYTheoDanhGia1 = new HashSet<SanPhamGoiYTheoDanhGia>();
        }
    
        public int SanPhamID { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public decimal Gia { get; set; }
        public Nullable<int> DanhMucID { get; set; }
        public int SoLuongKho { get; set; }
        public string ThuongHieu { get; set; }
        public string ViXuLy { get; set; }
        public string RAM { get; set; }
        public string LuuTru { get; set; }
        public string KichThuocManHinh { get; set; }
        public string MauSac { get; set; }
        public string DungLuongPin { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia1 { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhSanPham> HinhAnhSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamLienQuan> SanPhamLienQuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamLienQuan> SanPhamLienQuan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamThuongMuaCung> SanPhamThuongMuaCung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamThuongMuaCung> SanPhamThuongMuaCung1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserViews> UserViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamYeuThich> SanPhamYeuThich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSequence> ProductSequence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBehavior> UserBehavior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamGoiYTheoDanhGia> SanPhamGoiYTheoDanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamGoiYTheoDanhGia> SanPhamGoiYTheoDanhGia1 { get; set; }
    }
}
